### ISSUE TITLE
macOS / OS X Support?

### ISSUE THREAD

**Issue by MarQuisKnox** [Bendr0id/xmrigCC#38]
Is macOS / OS X Support planned? 
I get the errors below when trying to compile on macOS High Sierra 10.13.3:

````
Scanning dependencies of target xmrig_os_dependencies
[ 22%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/App_unix.cpp.o
[ 23%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/Cpu_mac.cpp.o
./.download/xmrigCC/src/Cpu_mac.cpp:33:6: error: use of undeclared identifier 'CpuImpl'
void CpuImpl::init()
     ^
./.download/xmrigCC/src/Cpu_mac.cpp:43:6: error: use of undeclared identifier 'CpuImpl'
void CpuImpl::setAffinity(int id, uint64_t mask)
     ^
2 errors generated.
make[2]: *** [CMakeFiles/xmrig_os_dependencies.dir/src/Cpu_mac.cpp.o] Error 1
make[1]: *** [CMakeFiles/xmrig_os_dependencies.dir/all] Error 2
make: *** [all] Error 2
````

**Comment by MarQuisKnox** [comment]
Fixed the first issue:  missing include:  `CpuImpl.h`
Fixed the second issue:  missing include:   `#include <string>`

Next issue, which I will review later unless you have an idea:

````
...
[ 46%] Built target xmrigCCServer
Scanning dependencies of target xmrigDaemon
[ 47%] Building CXX object CMakeFiles/xmrigDaemon.dir/src/cc/XMRigd.cpp.o
./.download/xmrigCC/src/cc/XMRigd.cpp:74:37: error: use of undeclared identifier 'EINTR'
    } while (WEXITSTATUS(status) == EINTR);
                                    ^
1 error generated.
make[2]: *** [CMakeFiles/xmrigDaemon.dir/src/cc/XMRigd.cpp.o] Error 1
make[1]: *** [CMakeFiles/xmrigDaemon.dir/all] Error 2
make: *** [all] Error 2
````

**Comment by Bendr0id** [comment]
Awesome, was about to write you.

For the last error please try to include errno.h

**Comment by MarQuisKnox** [comment]
Thanks for your response. I figured that one out already. 
Next issue is w/ RapidJSON:

````
-- Configuring done
-- Generating done
-- Build files have been written to: ./.download/xmrigCC
bash-3.2$ make
[  8%] Built target cpuid
[ 12%] Built target xmrig_cc_common
[ 15%] Built target xmrig_cpuid
[ 29%] Built target xmrig_common_cc
[ 38%] Built target xmrig_os_dependencies
[ 46%] Built target xmrigCCServer
[ 49%] Built target xmrigDaemon
[ 63%] Built target xmrig_common
[ 64%] Building CXX object CMakeFiles/xmrigMiner.dir/src/api/ApiState.cpp.o
In file included from ./.download/xmrigCC/src/api/ApiState.cpp:41: 
./.download/xmrigCC/src/3rdparty/rapidjson/document.h:1259:22: error: call to constructor of
      'rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >'
      is ambiguous
        GenericValue v(value);
                     ^ ~~~~~
./.download/xmrigCC/src/3rdparty/rapidjson/document.h:1330:16: note: in instantiation of function
      template specialization 'rapidjson::GenericValue<rapidjson::UTF8<char>,
      rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::AddMember<unsigned long>' requested here
        return AddMember(n, value, allocator);
               ^
./.download/xmrigCC/src/api/ApiState.cpp:227:9: note: in instantiation of function template
      specialization 'rapidjson::GenericValue<rapidjson::UTF8<char>,
      rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::AddMember<unsigned long>' requested here
    cpu.AddMember("sockets", Cpu::sockets(), allocator);
        ^
./.download/xmrigCC/src/3rdparty/rapidjson/document.h:634:14: note: candidate constructor
    explicit GenericValue(int i) RAPIDJSON_NOEXCEPT : data_() {
             ^
./.download/xmrigCC/src/3rdparty/rapidjson/document.h:640:14: note: candidate constructor
    explicit GenericValue(unsigned u) RAPIDJSON_NOEXCEPT : data_() {
             ^
./.download/xmrigCC/src/3rdparty/rapidjson/document.h:646:14: note: candidate constructor
    explicit GenericValue(int64_t i64) RAPIDJSON_NOEXCEPT : data_() {
             ^
./.download/xmrigCC/src/3rdparty/rapidjson/document.h:661:14: note: candidate constructor
    explicit GenericValue(uint64_t u64) RAPIDJSON_NOEXCEPT : data_() {
             ^
./.download/xmrigCC/src/3rdparty/rapidjson/document.h:673:14: note: candidate constructor
    explicit GenericValue(double d) RAPIDJSON_NOEXCEPT : data_() { data_.n.d = d; data_.f.flags = kNumbe...
             ^
1 error generated.
make[2]: *** [CMakeFiles/xmrigMiner.dir/src/api/ApiState.cpp.o] Error 1
make[1]: *** [CMakeFiles/xmrigMiner.dir/all] Error 2
````

**Comment by Bendr0id** [comment]
That's the old xmrig API. Try to remove ApiState.cpp from cmakelists.

Am 06.02.2018 22:31 schrieb MarQuis Knox <notifications@github.com>:

Thanks for your response. I figured that one out already.
Next issue is w/ RapidJSON:

-- Configuring done
-- Generating done
-- Build files have been written to: ./.download/xmrigCC
bash-3.2$ make
[  8%] Built target cpuid
[ 12%] Built target xmrig_cc_common
[ 15%] Built target xmrig_cpuid
[ 29%] Built target xmrig_common_cc
[ 38%] Built target xmrig_os_dependencies
[ 46%] Built target xmrigCCServer
[ 49%] Built target xmrigDaemon
[ 63%] Built target xmrig_common
[ 64%] Building CXX object CMakeFiles/xmrigMiner.dir/src/api/ApiState.cpp.o
In file included from ./.download/xmrigCC/src/api/ApiState.cpp:41:
./.download/xmrigCC/src/3rdparty/rapidjson/document.h:1259:22: error: call to constructor of
      'rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >'
      is ambiguous
        GenericValue v(value);
                     ^ ~~~~~
./.download/xmrigCC/src/3rdparty/rapidjson/document.h:1330:16: note: in instantiation of function
      template specialization 'rapidjson::GenericValue<rapidjson::UTF8<char>,
      rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::AddMember<unsigned long>' requested here
        return AddMember(n, value, allocator);
               ^
./.download/xmrigCC/src/api/ApiState.cpp:227:9: note: in instantiation of function template
      specialization 'rapidjson::GenericValue<rapidjson::UTF8<char>,
      rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::AddMember<unsigned long>' requested here
    cpu.AddMember("sockets", Cpu::sockets(), allocator);
        ^
./.download/xmrigCC/src/3rdparty/rapidjson/document.h:634:14: note: candidate constructor
    explicit GenericValue(int i) RAPIDJSON_NOEXCEPT : data_() {
             ^
./.download/xmrigCC/src/3rdparty/rapidjson/document.h:640:14: note: candidate constructor
    explicit GenericValue(unsigned u) RAPIDJSON_NOEXCEPT : data_() {
             ^
./.download/xmrigCC/src/3rdparty/rapidjson/document.h:646:14: note: candidate constructor
    explicit GenericValue(int64_t i64) RAPIDJSON_NOEXCEPT : data_() {
             ^
./.download/xmrigCC/src/3rdparty/rapidjson/document.h:661:14: note: candidate constructor
    explicit GenericValue(uint64_t u64) RAPIDJSON_NOEXCEPT : data_() {
             ^
./.download/xmrigCC/src/3rdparty/rapidjson/document.h:673:14: note: candidate constructor
    explicit GenericValue(double d) RAPIDJSON_NOEXCEPT : data_() { data_.n.d = d; data_.f.flags = kNumbe...
             ^
1 error generated.
make[2]: *** [CMakeFiles/xmrigMiner.dir/src/api/ApiState.cpp.o] Error 1
make[1]: *** [CMakeFiles/xmrigMiner.dir/all] Error 2

**Comment by MarQuisKnox** [comment]
OK. So close, but yet so far. I'm building from `master` BTW:

````
...
[ 97%] Building CXX object CMakeFiles/xmrigMiner.dir/src/cc/CCClient.cpp.o
[ 98%] Linking CXX executable xmrigMiner
Undefined symbols for architecture x86_64:
  "ApiState::tick(Hashrate const*)", referenced from:
      Api::tick(Hashrate const*) in Api.cpp.o
  "ApiState::tick(NetworkState const&)", referenced from:
      Api::tick(NetworkState const&) in Api.cpp.o
  "ApiState::ApiState()", referenced from:
      Api::start() in Api.cpp.o
  "ApiState::~ApiState()", referenced from:
      Api::release() in Api.cpp.o
  "ApiState::get(char const*, int*) const", referenced from:
      Api::get(char const*, int*) in Api.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [xmrigMiner] Error 1
make[1]: *** [CMakeFiles/xmrigMiner.dir/all] Error 2
make: *** [all] Error 2
````

**Comment by Bendr0id** [comment]
Remove API.cpp too.. it's also connected to the old xmrig API.

Am 06.02.2018 23:07 schrieb MarQuis Knox <notifications@github.com>:

OK. So close, but yet so far. I'm building from master BTW:

...
[ 97%] Building CXX object CMakeFiles/xmrigMiner.dir/src/cc/CCClient.cpp.o
[ 98%] Linking CXX executable xmrigMiner
Undefined symbols for architecture x86_64:
  "ApiState::tick(Hashrate const*)", referenced from:
      Api::tick(Hashrate const*) in Api.cpp.o
  "ApiState::tick(NetworkState const&)", referenced from:
      Api::tick(NetworkState const&) in Api.cpp.o
  "ApiState::ApiState()", referenced from:
      Api::start() in Api.cpp.o
  "ApiState::~ApiState()", referenced from:
      Api::release() in Api.cpp.o
  "ApiState::get(char const*, int*) const", referenced from:
      Api::get(char const*, int*) in Api.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [xmrigMiner] Error 1
make[1]: *** [CMakeFiles/xmrigMiner.dir/all] Error 2
make: *** [all] Error 2

**Comment by MarQuisKnox** [comment]
OK, works. 
Thanks!
